### ISSUE TITLE
[Election dApp] Implement interaction with election contract

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-governance-committee-voting#17]
**Task description**
Read details from an election contract instance, and allow users to submit a ballot to the contract.

- [x] Generate contract client
- [x] List election details
- [x] Submit election ballot to contract
- [x] Show ballot submission status
