### ISSUE TITLE
[guardian app] Implement guardian setup phase actions

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-governance-committee-voting#40]
As a guardian, I would like to be able to generate the key pair and decryption share for elections in their setup phase. If the parts received from other guardians are invalid, a corresponding complaint should be filed to the contract.

**Sub-tasks**
- [x] Enable setup actions only in the setup phase of the election
- [x] Generate private key, publish public key
- [x] Validate guardian keys + generate decryption share, publish encrypted share
- [x] Validate encrypted shares of other guardians, file complaint/signal OK
