### ISSUE TITLE
Enable querying delegation registrations for accounts

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-governance-committee-voting#46]
**Task description**
As a user, I would like to be able to see if my voting power delegation has been successfully registered. As delegation is done by submitting a transfer with a memo that needs to match a specific string according to the election configuration, merely checking the transaction status from a wallet will not be enough for the user.

**Sub-tasks**
- [x] Add delegation registrations to the database
- [x] Expose an endpoint for querying delegations related to an account
- [ ] Add page in the voting dApp for querying delegations + final weight for an account
